# This workflow will run a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go Aggregate Draft League

on:
  workflow_dispatch:

permissions: 
  contents: write

jobs:
  run:
    name: Run Go Program
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Run Go Program to Aggregate the Draft League
        run: make draft-league

      - name: Set Git Config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and Push JSON File of Updated League
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add data/view/aggregated-league-table.json
          git commit -m "Updating Aggregated League Table JSON" || echo "No changes to commit"
          git push origin HEAD
